version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "gainers:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - default
  influxdb:
    image: influxdb 
    ports:
      - "8086:8086"
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb
  influx_connector:
    image: kadek750/gainers:influx_connector
  spider:
    image: kadek750/gainers:spider
    depends_on:
      - default